package main

func main() {
	// mutatingMaps()
	// mapLiteralsContinued()
	// exerciseMaps()
	// functionValues()
	// functionClosures()
	// exerciseFibonacciClosur()
	// exerciseLoopsAndFunctions()
	// method()
	// methodsFunc()
	// methodsPointers()
	// interfaces()
	// interfaceValues()
	// errors()
	// exerciseErrors()
	// readers()
	// exerciseReader()
	// webServer()
	// exerciseWebServer()
	// exerciseImages()
	// exerciseRotReader()
	// goroutines()
	// channels()
	// befferedChannels()
	// rangeAndClose()
	// selects()
	// defaultSelection()
	// exerciseEquivalentBinaryTrees()
	exerciseWebCrawler()
}
